services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    # python main.py