services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    #tty: true
    #stdin_open: true
    command: sleep infinity